### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException

### ISSUE THREAD

**Issue by SABRYX** [gardencoder/react-native-paytabs-library#10]
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000116bee8db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001152cbac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000116b3cfac _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000116c5ae11 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x0000000116bea5bb +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5                                0x000000010e619976 __39-[RNPaytabsLibrary start:withCallBack:]_block_invoke_2.115 + 566
	6                                0x000000010e6040df -[PTFWInitialSetupViewController handleFinishTransactionEventWithTransactionResponseCode:andWithTransactionResult:andWithTransactionID:andWithTokenizedCustomerEmail:andWithTokenizedCustomerPassword:andWithPaytabsToken:andWithTransactionState:] + 415
	7                                0x000000010e6063f4 -[PTFWInitialSetupViewController handleErrorMessageBeforeTransaction:] + 100
	8                                0x000000010e60907f -[PTFWInitialSetupViewController isCommonRequestDataComplete] + 11167
	9                                0x000000010e60643c -[PTFWInitialSetupViewController performValidations] + 44
	10                               0x000000010e60306e -[PTFWInitialSetupViewController viewDidAppear:] + 94
	11  UIKitCore                           0x000000011f07d1f2 -[UIViewController _setViewAppearState:isAnimating:] + 942
	12  UIKitCore                           0x000000011f07db7e -[UIViewController _endAppearanceTransition:] + 196
	13  UIKitCore                           0x000000011ef931be -[UIPresentationController transitionDidFinish:] + 879
	14  UIKitCore                           0x000000011ef9c2fe -[_UICurrentContextPresentationController transitionDidFinish:] + 41
	15  UIKitCore                           0x000000011ef97434 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.425 + 183
	16  UIKitCore                           0x000000011f0a2698 -[_UIViewControllerTransitionContext completeTransition:] + 102
	17  UIKitCore                           0x000000011fb154d0 -[UITransitionView notifyDidCompleteTransition:] + 251
	18  UIKitCore                           0x000000011fb15147 -[UITransitionView _didCompleteTransition:] + 1381
	19  UIKitCore                           0x000000011fb17724 -[UITransitionView _transitionDidStop:finished:] + 104
	20  UIKitCore                           0x000000011fb1fe47 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 343
	21  UIKitCore                           0x000000011fb20469 -[UIViewAnimationState animationDidStop:finished:] + 293
	22  UIKitCore                           0x000000011fb2051d -[UIViewAnimationState animationDidStop:finished:] + 473
	23  QuartzCore                          0x000000011408cc5b _ZN2CA5Layer23run_animation_callbacksEPv + 321
	24  libdispatch.dylib                   0x000000011830bdb5 _dispatch_client_callout + 8
	25  libdispatch.dylib                   0x0000000118319080 _dispatch_main_queue_callback_4CF + 1540
	26  CoreFoundation                      0x0000000116b55a79 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	27  CoreFoundation                      0x0000000116b50126 __CFRunLoopRun + 2310
	28  CoreFoundation                      0x0000000116b4f4d2 CFRunLoopRunSpecific + 626
	29  GraphicsServices                    0x000000011bc422fe GSEventRunModal + 65
	30  UIKitCore                           0x000000011f679fc2 UIApplicationMain + 140
	31                               0x000000010d9bfe90 main + 112
	32  libdyld.dylib                       0x0000000118380541 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by SABRYX** [comment]
@gardencoder  can u help with this ?

**Comment by gardencoder** [comment]
@SABRYX  Hey, i am sorry for late reply, can you please give me sample code how you call the library ? and your inputs?

**Comment by SABRYX** [comment]
@gardencoder  Hey Rami This issue was resolved by Changing country_billing back to BHR
