### ISSUE TITLE
Can't Find the Repo Publish on NPM

### ISSUE THREAD

**Issue by SABRYX** [gardencoder/react-native-paytabs-library#7]
```
npm ERR! code E404
npm ERR! 404 Not Found: @gardencoder/react-native-paytabs-library@1.0.3
```

**Comment by gardencoder** [comment]
@SABRYX  Please check this https://help.github.com/en/github/managing-packages-with-github-package-registry/configuring-npm-for-use-with-github-package-registry#installing-a-package

**Comment by SABRYX** [comment]
@gardencoder This does install it thanks
